AllCops:
  TargetRubyVersion: 2.5

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "bin/*"

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false
